[package]
name = "process-core"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
anyhow.workspace = true
chrono.workspace = true
serde_yaml.workspace = true
